version: '3.4'

services:
  kpapi:
    container_name: api
    image: kpapi
    build:
      context: .
      dockerfile: API.Dockerfile
    ports:
      - 5000:5000
    networks:
     - m-proxy-net
    #depends_on:
    #  - dbs
  view:
      container_name: view
      image : kpview
      build:
         context: .
         dockerfile: View.Dockerfile
      depends_on:
         - kpapi
      ports:
      - 8080:80
      networks:
         - m-proxy-net
networks:
   m-proxy-net:
    external:
      name: custom_network
